import {ArrowRight, Check, ChevronsUpDown, Circle, Copy, CreditCard, DollarSign, Edit, ExternalLink, File, HelpCircle, Home, Info, Loader2, Mail, MessageSquare, Moon, PiggyBank, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, Sun, Trash, User, Workflow, AlertTriangle, Wallet, ListChecks, TrendingUp, Brain, Bot, X } from 'lucide-react'; // Added X

const Icons = {
  alertTriangle: AlertTriangle,
  arrowRight: ArrowRight,
  bot: Bot,
  brain: Brain,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  close: X, // X is now imported
  copy: Copy,
  creditCard: CreditCard,
  dark: Moon,
  dollarSign: DollarSign,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  info: Info,
  light: Sun,
  listChecks: ListChecks,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  piggyBank: PiggyBank,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  trendingUp: TrendingUp,
  user: User,
  wallet: Wallet,
  workflow: Workflow,
};

export {Icons};
